/*:
 * @target MZ
 * @author Comuns
 * @plugindesc Typescript plugin archetype
 * @help Typescript Plugin Archetype.
 * 
 * This is a plugin archetype, it does not provide any functionality, only a
 * template for other plugins.
 */

//=============================================================================
// ** NOTICE **
//-----------------------------------------------------------------------------
// The code below is generated by a compiler, and is not well suited for human
// reading. If you are interested on the source code, please take a look at
// the Github repository for this plugin!
//=============================================================================

this.J = this.J || {};
this.J.CMS = (function (exports) {
    'use strict';

    var Aliased = {
        Window_MenuCommand: {},
    };
    function sayHi() {
        console.log("Hello " + window.$dataSystem.gameTitle + "!");
    }
    Aliased.Window_MenuCommand.makeCommandList = window.Window_MenuCommand.prototype.makeCommandList;
    window.Window_MenuCommand.prototype.makeCommandList = function () {
        Aliased.Window_MenuCommand.makeCommandList.call(this);
        console.log("hello world");
    };

    exports.sayHi = sayHi;

    return exports;

}({}));
//# sourceMappingURL=J-CMS.debug.js.map
