/**
 * The structure of a minimap event type.
 */
class MinimapEventType
{
  /**
   * The string value of the type of this minimap event type.
   * @type {string}
   */
  type = 'unset';

  /**
   * The color to render onto the minimap.
   * @type {string}
   */
  color = '#aa66ffcc';

  /**
   * The default shape to render for this minimap event type.
   * Supported: 'disk' | 'square' | 'diamond' | 'plus'
   * @type {string}
   */
  shape = 'disk';

  /**
   * The various shapes that a minimap event marker can be.
   * @type {{Disk: string, Square: string, Diamond: string, Plus: string}}
   */
  static Shapes = {
    Disk: 'disk',
    Square: 'square',
    Diamond: 'diamond',
    Plus: 'plus',
    HollowSquare: 'hollow-square',
  };

  /**
   * The minimap event type of unset, used for when an event explicitly does not have a minimap tag on it.
   * @type {MinimapEventType}
   */
  static Unset = new MinimapEventType('unset', '#99999999', MinimapEventType.Shapes.Disk);

  /**
   * The minimap event type of Player, used for rendering the player onto the minimap.
   * @type {MinimapEventType}
   */
  static Player = new MinimapEventType('player', '#00aaaacc', MinimapEventType.Shapes.Plus);

  /**
   * The minimap event type of Follower, used for rendering your party allies onto the minimap.
   * @type {MinimapEventType}
   */
  static Follower = new MinimapEventType('follower', '#44aaffcc', MinimapEventType.Shapes.Square);

  /**
   * The minimap event type of Enemy, used for rendering hostile combatants onto the minimap.
   * @type {MinimapEventType}
   */
  static EnemyHostile = new MinimapEventType('enemyHostile', '#ff4444cc', MinimapEventType.Shapes.Diamond);

  /**
   * The minimap event type of Inanimate, used for rendering inanimate objects that are backed by an enemy onto the
   * minimap.
   * @type {MinimapEventType}
   */
  static EnemyInanimate = new MinimapEventType('enemyInanimate', '#ffaa44cc', MinimapEventType.Shapes.Diamond);

  /**
   * The minimap event type of NPC, used for various characters that aren't that important.
   * @type {MinimapEventType}
   */
  static Npc = new MinimapEventType('npc', '#dd66ffcc', MinimapEventType.Shapes.Disk);

  /**
   * The minimap event type of loot, used for events generated by loot dropped on the ground.
   * @type {MinimapEventType}
   */
  static Loot = new MinimapEventType('loot', '#44ff66cc', MinimapEventType.Shapes.Diamond);

  /**
   * The minimap event type of object, used for various interactables around the game like doors or levers.
   * @type {MinimapEventType}
   */
  static Object = new MinimapEventType('object', '#dddd00cc', MinimapEventType.Shapes.Diamond);

  /**
   * The minimap event type of teleport, rendered as a hollow square. May stretch if <areaEvent:WxH> is present.
   * @type {MinimapEventType}
   */
  static Teleport = new MinimapEventType('teleport', '#66ccffcc', MinimapEventType.Shapes.HollowSquare);

  /**
   * The minimap event type for quests: offer available (not yet started).
   * @type {MinimapEventType}
   */
  static QuestOffer = new MinimapEventType('questOffer', '#ffdd33cc', MinimapEventType.Shapes.Square);

  /**
   * The minimap event type for quests: can progress the next objective here.
   * @type {MinimapEventType}
   */
  static QuestProgress = new MinimapEventType('questProgress', '#3399ffcc', MinimapEventType.Shapes.Diamond);

  /**
   * The minimap event type for quests: turn-in / about to complete.
   * @type {MinimapEventType}
   */
  static QuestTurnIn = new MinimapEventType('questTurnIn', '#66ff66cc', MinimapEventType.Shapes.Disk);

  constructor(type, color = '#00000066', shape = 'disk')
  {
    this.type = type;
    this.color = color;
    this.shape = shape;
  }
}