//region initialization
/**
 * The core where all of my extensions live: in the `J` object.
 */
var J = J || {};

//region version checks
(() =>
{
  // Check to ensure we have the minimum required version of the J-Base plugin.
  const requiredBaseVersion = '3.0.0';
  const hasBaseRequirement = J.BASE.Helpers.satisfies(J.BASE.Metadata.Version, requiredBaseVersion);
  if (!hasBaseRequirement)
  {
    throw new Error(`Either missing J-Base or has a lower version than the required: ${requiredBaseVersion}`);
  }

  // Check to ensure we have the minimum required version of the J-ABS plugin.
  const requiredJabsVersion = '4.5.0';
  const hasJabsRequirement = J.BASE.Helpers.satisfies(J.ABS.Metadata.Version, requiredJabsVersion);
  if (!hasJabsRequirement)
  {
    throw new Error(`Either missing J-ABS or has a lower version than the required: ${requiredJabsVersion}`);
  }
})();
//endregion version check

J.ABS.EXT.FORMULA = {};

/**
 * The metadata associated with this plugin.
 */
J.ABS.EXT.FORMULA.Metadata = new JFORMULA_PluginMetadata('J-ABS-Formula', '1.0.0');

/**
 * A collection of all aliased methods for this plugin.
 */
J.ABS.EXT.FORMULA.Aliased = {};
J.ABS.EXT.FORMULA.Aliased.Game_Action = new Map();
J.ABS.EXT.FORMULA.Aliased.JABS_Engine = new Map();

/**
 * Execution-time context flags and helpers for this extension.
 */
J.ABS.EXT.FORMULA.Context = {
  /**
   * Whether sub-executions should suppress cascading of this extension.
   */
  suppressCascades: false,

  /**
   * Whether to suppress applyGlobal() (i.e., skip child skill common events).
   */
  suppressCommonEvents: false,

  /**
   * The active trigger while applying packets ("hit" | "use").
   */
  activeTrigger: null,

  /**
   * Buffer for action log entries generated by this extension during
   * a single Game_Action application. Flushed by the wrapper.
   * @type {ActionLog[]}
   */
  logBuffer: [],
};

/**
 * Runtime behavior for log flushing.
 */
J.ABS.EXT.FORMULA.Settings = {
  /**
   * When to flush buffered logs for this extension relative to the core flow.
   * Options: "after-base" | "before-base".
   * Note: for on-hit packets you generally want "after-base".
   */
  logFlushTiming: "after-base",

  /**
   * Prefer appending if supported by the manager (so base logs remain visually first).
   */
  preferAppend: true,
};

/**
 * All regular expressions used by this plugin.
 */
J.ABS.EXT.FORMULA.RegExp = {};
J.ABS.EXT.FORMULA.RegExp.FormulaApply =
  /<on-(hit|use):to-(self|allies|target|enemies|all):by-formula:for-(hp|mp|tp):\[([+\-*/ ().\w]+)]>/gi;
J.ABS.EXT.FORMULA.RegExp.SkillApply =
  /<on-(hit|use):to-(self|allies|target|enemies|all):by-skill:\[(\d+)]>/gi;
//endregion initialization