//region Introduction
/*:
 * @target MZ
 * @plugindesc
 * [v@@PLUGIN_VERSION@@ @@PLUGIN_DESC_TAG@@] Combat and reward popups for JABS.
 * @author JE
 * @url https://github.com/je-can-code/rmmz-plugins
 * @base J-Base
 * @base J-Popups
 * @base J-ABS
 * @orderAfter J-Base
 * @orderAfter J-Popups
 * @orderAfter J-ABS
 * @param disableSkillUsedPopups
 * @text Disable skill-used popups
 * @type boolean
 * @default false
 * @desc When true, hides the floating skill name on the caster only; damage/healing/reward popups still show.
 * @param enableMergeCombat
 * @text Merge combat strike numbers
 * @type boolean
 * @default true
 * @desc Sum incoming strikes on the target into one stream per HP/MP/TP line (who-hit-you lives in logs).
 * @param enableMergeSlip
 * @text Merge slip/regen ticks
 * @type boolean
 * @default true
 * @desc Sum slip/regen ticks on the battler into one stream per resource line until flush.
 * @param enableMergeRewards
 * @text Merge reward totals (exp/gold/AP/SDP)
 * @type boolean
 * @default true
 * @desc Sum numeric reward pops before releasing motion.
 * @param enableMergeMitigation
 * @text Stack mitigation labels (parry/dodge counts)
 * @type boolean
 * @default true
 * @desc Shows PARRY xN / DODGE xN style stacks before releasing motion.
 * @param mergeIdleFlushFrames
 * @text Idle flush frames
 * @type number
 * @default 90
 * @min 1
 * @desc Release after this many frames with no merge **on this battler** (any stream counts).
 * @param damageOutlineWidth
 * @text Harm outline width
 * @type number
 * @min 0
 * @max 8
 * @decimals 0
 * @default 2
 * @desc Pixel width of the outline on harm HP/MP/TP combat damage numbers.
 * @param healingOutlineWidth
 * @text Heal outline width
 * @type number
 * @min 0
 * @max 8
 * @decimals 0
 * @default 4
 * @desc Pixel width of the outline on heal HP/MP/TP combat regen numbers.
 * @help
 * ============================================================================
 * OVERVIEW
 * This plugin is an extension of J-Popups for J-ABS.
 *
 * Have you ever wanted floating popups for all of that glorious combat chaos
 * your JABS game dishes out- damage numbers, healing, experience, gold, loot,
 * level-ups, and skill learns? Well now you can! This plugin wires up popup
 * builders for every major JABS combat and reward event.
 *
 * ----------------------------------------------------------------------------
 * DETAILS:
 * Popup construction is handled through JABS_PopupManager, which provides
 * dedicated builder methods for each popup type. All popups are displayed on
 * the relevant battler's or character's map sprite.
 *
 * ============================================================================
 * NOTETAGS:
 * The following notetags are supported by this plugin. Place them in the
 * note field of a STATE only.
 *
 * <noHpPopup>
 *    Suppresses HP slip/regen popups generated by this state.
 *
 * <noMpPopup>
 *    Suppresses MP slip/regen popups generated by this state.
 *
 * <noTpPopup>
 *    Suppresses TP slip/regen popups generated by this state.
 *
 * <noSlipPopup>
 *    Suppresses ALL slip/regen popups (HP, MP, and TP) generated by this state.
 *
 * ============================================================================
 * CHANGELOG:
 * - 1.3.0
 *    Per-target strike/slip aggregates (no per-attacker lanes); combat slip/reward/mitigation merge buckets +
 *    idle/combo/map flush hooks; requires J-Popups v2.1.0+ merge stack (`Sprite_MapDamage`, merge controller).
 *    `mergeIdleFlushFrames` is one sliding window per target (all merge kinds refresh it); strike release does not
 *    listen on `ComboChainCleared` (avoids global flush from other battlers' cooldowns).
 *    Added <noHpPopup>/<noMpPopup>/<noTpPopup>/<noSlipPopup> state tags to
 *    suppress slip/regen popups per-resource or entirely.
 *    Added configurable outline width plugin params for harm vs heal
 *    combat damage numbers (damageOutlineWidth/healingOutlineWidth).
 * - 1.2.0
 *    Plugin parameter disableSkillUsedPopups suppresses caster skill-name popups only.
 * - 1.1.0
 *    Extracted popup construction into a dedicated JABS_PopupManager class.
 *    Added ABS-specific TextPopBuilder and Map_TextPop extensions in _models/.
 *    Renamed source files to standard JABS naming conventions.
 * - 1.0.0
 *    Initial release.
 * ============================================================================
 */
//endregion Introduction