//region annotations
/*:
 * @target MZ
 * @plugindesc [v@@PLUGIN_VERSION@@ @@PLUGIN_DESC_TAG@@] JS Mods exclusive to Chef Adventure.
 * @author JE
 * @url https://github.com/je-can-code/rmmz-plugins
 * @help
 * ============================================================================
 * OVERVIEW
 * These modifications of code are modifications against various components of
 * the core scripts. Additionally, plugins I've written are also modified here
 * in a way that I consider "not-mainstream enough" to be published as a part
 * of the original plugins.
 *
 * NOTE ABOUT USING THIS "PLUGIN":
 * While I do list below the various changes that are provided by this plugin
 * modifier, I do not intend to support this as a public plugin, so you should
 * probably not use this plugin unless you want 100% of the functionality
 * listed below, or are able to tweak/adjust the code yourself.
 *
 * This is also NOT a versioned plugin, and can potentially change without
 * any notification.
 *
 * Use with caution!
 *
 * ============================================================================
 * SYSTEM CHANGES:
 * - additional equip slot for all actors (as accessory)
 * - "recover all" recovers TP too
 * - random variable assignment for "rare/named enemies" on map transfer
 *
 * ----------------------------------------------------------------------------
 * CA-UNIQUE CHANGES:
 * - inanimate enemies grant no rewards of any kind
 * - anti-null elementIds hard-coded
 * - target frame text autogenerated from the four CA "trait" elements
 * - helpers for locating the elemental allies by actor id
 * ============================================================================
 */
//endregion annotations