//region annotations
/*:
 * @target MZ
 * @plugindesc [v@@PLUGIN_VERSION@@ @@PLUGIN_DESC_TAG@@] JS Mods exclusive to Chef Adventure.
 * @author JE
 * @url https://github.com/je-can-code/rmmz-plugins
 * @help
 * ============================================================================
 * OVERVIEW
 * These modifications of code are modifications against various components of
 * the core scripts. Additionally, plugins I've written are also modified here
 * in a way that I consider "not-mainstream enough" to be published as a part
 * of the original plugins.
 *
 * NOTE ABOUT USING THIS "PLUGIN":
 * While I do list below the various changes that are provided by this plugin
 * modifier, I do not intend to support this as a public plugin, so you should
 * probably not use this plugin unless you want 100% of the functionality
 * listed below, or are able to tweak/adjust the code yourself.
 *
 * This is also NOT a versioned plugin, and can potentially change without
 * any notification.
 *
 * Use with caution!
 *
 * ============================================================================
 * SYSTEM CHANGES:
 * - additional equip slot for all actors (as accessory)
 * - "recover all" recovers TP too
 * - random variable assignment for "rare/named enemies" on map transfer
 *
 * ----------------------------------------------------------------------------
 * CA-UNIQUE CHANGES:
 * - inanimate enemies grant no rewards of any kind
 * - loot drop x,y adjustment unique to CA
 * - anti-null elementIds hard-coded
 * - target frame text autogenerated from the four CA "trait" elements
 * - helpers for locating the elemental allies by actor id
 * - mini floor-damage system built with tags (TODO: replace with plugin?)
 *
 * ============================================================================
 * FLOOR DAMAGE:
 * A minimal, tag-driven damage-floor system (TODO: replace with a proper
 * plugin). Damage is summed from every source in floorDamageSources()
 * (currently just the current map's own note) whenever the actor steps.
 *
 * TAG USAGE:
 * - Maps (the map note field)
 *
 * TAG FORMAT:
 *  <damageFlat:VALUE>
 *    Where VALUE is a flat HP damage amount taken per step.
 *
 *  <damagePerc:VALUE>
 *    Where VALUE is a percent of the actor's max HP taken per step.
 *
 * TAG EXAMPLES:
 *  <damageFlat:10>
 * Stepping anywhere on this map deals 10 flat HP damage.
 *
 *  <damagePerc:5>
 * Stepping anywhere on this map deals 5% of the actor's max HP.
 *
 * NOTE: Multiple tags of the same kind on the map note are all summed
 * together (flat sums directly; percent sums are each calculated against
 * max HP individually, then summed).
 * ============================================================================
 */
//endregion annotations