import './_metadata/initialization.js';
import './models/CollapseMotionEffect.js';
import './core/registerCollapseMotionType.js';
import './core/DeathMotionResolver.js';
import './managers/BattlerMotionCoordinator.js';
import './managers/LootMotionCoordinator.js';
import './objects/Game_Battler.js';
import './managers/JABS_Engine.js';
import './sprites/Sprite_Character.js';